name: render_studio
description: A new Flutter project.

publish_to: 'none'

version: 2.7.6+4

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Dependencies
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  cloud_firestore: ^4.0.5
  firebase_storage: ^11.0.5
  firebase_crashlytics: ^3.0.5
  firebase_performance: ^0.9.0+5
  firebase_analytics: ^10.0.5
  firebase_dynamic_links: ^5.0.5
  firebase_remote_config: ^3.0.5

  auto_animated: ^3.0.1
  property_change_notifier: ^0.3.0
  align_positioned: ^3.0.0
  animations: ^2.0.2
  app_settings: ^4.1.1
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.5
  dio: ^4.0.4
  dotted_border: ^2.0.0+2
  dotted_line: ^3.0.0
  file_picker: ^5.2.2
  flutter_colorpicker: ^1.0.3
  flutter_staggered_grid_view: ^0.6.0
  flutter_svg: ^1.0.2
  font_awesome_flutter: ^10.1.0
  get: ^4.1.4
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  image_cropper: ^3.0.1
  image_gallery_saver: ^1.7.1
  octo_image: ^1.0.1
  package_info: ^2.0.2
  palette_generator: ^0.3.0
  path_provider: ^2.0.2
  permission_handler: ^9.2.0
  provider: ^6.0.2
  screenshot: ^1.2.3
  share_plus: ^6.3.0
  shared_preferences: ^2.0.6
  supercharged: ^2.1.1
  timeago: ^3.1.0
  url_launcher: ^6.0.6
  device_info: ^2.0.3
  flutter_spinkit: ^5.1.0
  flip_card: ^0.6.0
  qr_flutter: ^4.0.0
  flutter_palette: ^1.1.0+1
  universal_io: ^2.0.4
  image_picker: ^0.8.6
  skeletons: ^0.0.3
  on_image_matrix: ^1.0.0+1
  device_info_plus: ^8.0.0
  flutter_dotenv: ^5.0.2
  flutter_slidable: ^2.0.0
  flutter_reorderable_grid_view: ^3.1.3
  iconsax: ^0.0.8
  image_pixels: ^3.0.0
  colorfilter_generator: ^0.0.8
  image_editor: ^1.3.0
  infinite_scroll_pagination: ^3.2.0
  flutter_blurhash: ^0.7.0
  sprung: ^3.0.1
  star_menu: ^3.1.0+1
  badges: ^2.0.3
  code_editor: ^1.3.2
  slinky_view: ^1.0.1
  flutter_reorderable_list: ^1.2.0
  extended_text: ^9.1.2
  neopop: ^1.0.2
  phosphor_flutter: any
  go_router: ^5.2.4
  gesture_x_detector: ^1.1.1
  zoom_widget: ^2.0.0
  styled_text: ^6.0.0
  easy_rich_text: ^1.1.0
  percent_indicator: ^4.2.2
  dashed_circular_progress_bar: ^0.0.4
  fl_chart: ^0.55.2
  auto_size_text: ^3.0.0
  pie_chart: ^5.3.2
  flutter_slider_drawer: ^2.1.2
  flutter_advanced_drawer: ^1.3.2
  flutter_scrolling_fab_animated: ^0.1.4
  google_sign_in: ^5.4.2
  sign_in_with_apple: ^4.3.0
  animated_text_kit: ^4.2.2
  animate_do: ^3.0.2
  animate_gradient: ^0.0.2
  smooth_page_indicator: ^1.0.0+2
  auto_size_widget: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.10.0
  # flutter_lints: ^1.0.0

## Generate app icons for Android and iOS
## Run command: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/render.env
    - assets/images/avatar.png
    - assets/icon.png
    - assets/intro/1.jpg
    - assets/intro/2.jpg
    - assets/intro/3.jpg
    - assets/intro/4.jpg
    - assets/intro/5.jpg

  fonts:
    - family: Google Sans
      fonts:
        - asset: "assets/fonts/Google Sans/Regular.ttf"
          weight: 300
        - asset: "assets/fonts/Google Sans/Regular-Italic.ttf"
          weight: 300
          style: italic
        - asset: "assets/fonts/Google Sans/Medium.ttf"
          weight: 500
        - asset: "assets/fonts/Google Sans/Medium-Italic.ttf"
          weight: 500
          style: italic
        - asset: "assets/fonts/Google Sans/Bold.ttf"
          weight: 700
        - asset: "assets/fonts/Google Sans/Bold-Italic.ttf"
          weight: 700
          style: italic
    - family: DM Serif Display
      fonts:
        - asset: "assets/fonts/DM Serif Display/Regular.ttf"
          weight: 300
        - asset: "assets/fonts/DM Serif Display/Italics.ttf"
          weight: 300
          style: italic
    - family: Circular
      fonts:
        - asset: "assets/fonts/Circular/Regular.ttf"
          weight: 500
    - family: Inter
      fonts:
        - asset: "assets/fonts/Inter/Thin.ttf"
          weight: 100
        - asset: "assets/fonts/Inter/ExtraLight.ttf"
          weight: 200
        - asset: "assets/fonts/Inter/Light.ttf"
          weight: 300
        - asset: "assets/fonts/Inter/Regular.ttf"
          weight: 400
        - asset: "assets/fonts/Inter/Medium.ttf"
          weight: 500
        - asset: "assets/fonts/Inter/SemiBold.ttf"
          weight: 600
        - asset: "assets/fonts/Inter/Bold.ttf"
          weight: 700
        - asset: "assets/fonts/Inter/ExtraBold.ttf"
          weight: 800
        - asset: "assets/fonts/Inter/Black.ttf"
          weight: 900
    - family: Red Hat
      fonts:
        - asset: "assets/fonts/Red Hat/Display-Light.ttf"
          weight: 300
        - asset: "assets/fonts/Red Hat/Display-Light.ttf"
          weight: 300
          style: italic
        - asset: "assets/fonts/Red Hat/Display-Regular.ttf"
          weight: 400
        - asset: "assets/fonts/Red Hat/Display-Italic.ttf"
          weight: 400
          style: italic
        - asset: "assets/fonts/Red Hat/Display-Medium.ttf"
          weight: 500
        - asset: "assets/fonts/Red Hat/Display-MediumItalic.ttf"
          weight: 500
          style: italic
        - asset: "assets/fonts/Red Hat/Display-SemiBold.ttf"
          weight: 600
        - asset: "assets/fonts/Red Hat/Display-SemiBoldItalic.ttf"
          weight: 600
          style: italic
        - asset: "assets/fonts/Red Hat/Display-Bold.ttf"
          weight: 700
        - asset: "assets/fonts/Red Hat/Display-BoldItalic.ttf"
          weight: 700
          style: italic
        - asset: "assets/fonts/Red Hat/Display-ExtraBold.ttf"
          weight: 800
        - asset: "assets/fonts/Red Hat/Display-ExtraBoldItalic.ttf"
          weight: 800
          style: italic
        - asset: "assets/fonts/Red Hat/Display-Black.ttf"
          weight: 900
        - asset: "assets/fonts/Red Hat/Display-BlackItalic.ttf"
          weight: 900
          style: italic
    - family: Helvetica
      fonts:
        - asset: "assets/fonts/Helvetica/Thin.ttf"
          weight: 100
        - asset: "assets/fonts/Helvetica/Thin-Italic.ttf"
          weight: 100
          style: italic
        - asset: "assets/fonts/Helvetica/Light.ttf"
          weight: 300
        - asset: "assets/fonts/Helvetica/Light-Italic.ttf"
          weight: 300
          style: italic
        - asset: "assets/fonts/Helvetica/Regular.ttf"
          weight: 400
        - asset: "assets/fonts/Helvetica/Regular-Italic.ttf"
          weight: 400
          style: italic
        - asset: "assets/fonts/Helvetica/Medium.ttf"
          weight: 500
        - asset: "assets/fonts/Helvetica/Medium-Italic.ttf"
          weight: 500
          style: italic
        - asset: "assets/fonts/Helvetica/Bold.ttf"
          weight: 700
        - asset: "assets/fonts/Helvetica/Bold-Italic.ttf"
          weight: 700
          style: italic
        - asset: "assets/fonts/Helvetica/Extra-Bold.ttf"
          weight: 800
        - asset: "assets/fonts/Helvetica/Extra-Bold-Italic.ttf"
          weight: 800
          style: italic
        - asset: "assets/fonts/Helvetica/Black.ttf"
          weight: 900
        - asset: "assets/fonts/Helvetica/Black-Italic.ttf"
          weight: 900
          style: italic
    - family: SF Pro
      fonts:
        - asset: "assets/fonts/SF Pro/Regular.ttf"
          weight: 400