name: render_studio
description: A new Flutter project.

publish_to: 'none'

version: 2.9.0+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Dependencies
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5
  firebase_storage: ^11.0.16
  firebase_crashlytics: ^3.0.17
  firebase_performance: ^0.9.0+16
  firebase_analytics: ^10.1.6
  firebase_dynamic_links: ^5.0.17
  firebase_remote_config: ^4.2.0

  auto_animated: ^3.0.1
  property_change_notifier: ^0.3.0
  align_positioned: ^3.0.0
  animations: ^2.0.2
  app_settings: ^5.0.0
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.5
  dio: ^5.1.2
  dotted_border: ^2.0.0+2
  dotted_line: ^3.0.0
  file_picker: ^5.2.2
  flutter_colorpicker: ^1.0.3
  flutter_staggered_grid_view: ^0.6.0
  flutter_svg: ^2.0.0
  font_awesome_flutter: ^10.1.0
  get: ^4.1.4
  google_fonts: ^5.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  image_cropper: ^5.0.0
  image_gallery_saver: ^2.0.3
  octo_image: ^1.0.1
  palette_generator: ^0.3.0
  path_provider: ^2.0.2
  permission_handler: ^10.2.0
  provider: ^6.0.2
  screenshot:
    git:
      url: https://github.com/Mayb3Nots/screenshot.git
      ref: master
  share_plus: ^7.0.0
  shared_preferences: ^2.2.0
  supercharged: ^2.1.1
  timeago: ^3.1.0
  url_launcher: ^6.0.6
  flutter_spinkit: ^5.1.0
  flip_card: ^0.7.0
  qr_flutter: ^4.0.0
  flutter_palette: ^1.1.0+1
  universal_io: ^2.0.4
  image_picker: ^1.0.1
  skeletons: ^0.0.3
  device_info_plus: ^9.0.0
  flutter_dotenv: ^5.0.2
  flutter_slidable: ^3.0.0
  flutter_reorderable_grid_view: ^4.0.0
  iconsax: ^0.0.8
  image_pixels: ^3.0.0
  colorfilter_generator: ^0.0.8
  image_editor: ^1.3.0
  infinite_scroll_pagination: ^3.2.0
  flutter_blurhash: ^0.7.0
  sprung: ^3.0.1
  star_menu: ^3.1.0+1
  badges: ^3.0.2
  code_editor: ^1.3.2
  slinky_view: ^1.0.1
  flutter_reorderable_list: ^1.2.0
  extended_text: ^11.0.1
  neopop: ^1.0.2
  phosphor_flutter: any
  go_router: ^10.0.0
  gesture_x_detector: ^1.1.1
  zoom_widget: ^2.0.0
  styled_text: ^8.1.0
  easy_rich_text: ^2.0.0
  percent_indicator: ^4.2.2
  dashed_circular_progress_bar: ^0.0.4
  fl_chart: ^0.63.0
  auto_size_text: ^3.0.0
  pie_chart: ^5.3.2
  flutter_slider_drawer: ^2.1.2
  flutter_advanced_drawer: ^1.3.2
  flutter_scrolling_fab_animated: ^0.1.4
  google_sign_in: ^6.1.0
  sign_in_with_apple: ^5.0.0
  animated_text_kit: ^4.2.2
  animate_do: ^3.0.2
  animate_gradient: ^0.0.2
  smooth_page_indicator: ^1.0.0+2
  auto_size_widget: ^0.0.4
  touch_ripple_effect: ^2.2.4
  faded_widget: ^2.0.0
  dynamic_color: ^1.5.4

  flutter_material_symbols: ^0.0.4
  assorted_layout_widgets: ^8.0.0
  extended_icon_button: ^1.0.0
  animated_splash_screen: ^1.3.0
  zwidget: ^0.0.2
  flutter_native_splash: ^2.2.16
  lottie: ^2.2.0
  google_mobile_ads: ^3.0.0
  package_info_plus: ^4.0.0
  open_store: ^0.5.0
  reorderable_grid_view: ^2.2.5
  sliver_tools: ^0.2.9
  figma_squircle: ^0.5.3
  smooth_corner: ^1.1.0
  flutter_animate: ^4.2.0+1
  animated_switcher_plus: ^1.1.0
  mesh_gradient: ^1.1.5
  blur: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  # flutter_lints: ^1.0.0

## Generate app icons for Android and iOS
## Run command: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21

## Generate splash screen for Android and iOS
## Run command: flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#0b0d0f"
  image: assets/icon.png

flutter:

  uses-material-design: true

  assets:
    - assets/render.env
    - assets/images/
    - assets/icon.png
    - assets/fonts/
    - assets/animations/

  fonts:
    
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist/Thin.otf
          weight: 100
        - asset: assets/fonts/Geist/UltraLight.otf
          weight: 200
        - asset: assets/fonts/Geist/Light.otf
          weight: 300
        - asset: assets/fonts/Geist/Regular.otf
          weight: 400
        - asset: assets/fonts/Geist/Medium.otf
          weight: 500
        - asset: assets/fonts/Geist/SemiBold.otf
          weight: 600
        - asset: assets/fonts/Geist/Bold.otf
          weight: 700
        - asset: assets/fonts/Geist/Black.otf
          weight: 800
        - asset: assets/fonts/Geist/UltraBlack.otf
          weight: 900

    - family: Geist Mono
      fonts:
        - asset: assets/fonts/Geist Mono/Thin.otf
          weight: 100
        - asset: assets/fonts/Geist Mono/UltraLight.otf
          weight: 200
        - asset: assets/fonts/Geist Mono/Light.otf
          weight: 300
        - asset: assets/fonts/Geist Mono/Regular.otf
          weight: 400
        - asset: assets/fonts/Geist Mono/Medium.otf
          weight: 500
        - asset: assets/fonts/Geist Mono/SemiBold.otf
          weight: 600
        - asset: assets/fonts/Geist Mono/Bold.otf
          weight: 700
        - asset: assets/fonts/Geist Mono/Black.otf
          weight: 800
        - asset: assets/fonts/Geist Mono/UltraBlack.otf
          weight: 900

    - family: SF Pro Rounded
      fonts:
        - asset: assets/fonts/SF Pro/Rounded-Ultralight.otf
          weight: 100
        - asset: assets/fonts/SF Pro/Rounded-Thin.otf
          weight: 200
        - asset: assets/fonts/SF Pro/Rounded-Light.otf
          weight: 300
        - asset: assets/fonts/SF Pro/Rounded-Regular.otf
          weight: 400
        - asset: assets/fonts/SF Pro/Rounded-Medium.otf
          weight: 500
        - asset: assets/fonts/SF Pro/Rounded-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF Pro/Rounded-Bold.otf
          weight: 700
        - asset: assets/fonts/SF Pro/Rounded-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF Pro/Rounded-Black.otf
          weight: 900